name: Weekly Build for 1.19

on:
  schedule:
    - cron: "0 5 * * TUE"
  workflow_dispatch:

env:
  TAG_VERSION: 1.19
  MC_VERSION: 1.19.2
  JAVA_VERSION: 17
  BRANCH: 1.19

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/kotori316/fictional-meme/fictional-meme:${{ env.TAG_VERSION }}
          push: true
          build-args: |
            MINECRAFT_VERSION=${{ env.MC_VERSION }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            PARCHMENT_MINECRAFT_VERSION=1.19.2

  check:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/kotori316/fictional-meme/fictional-meme:${{ env.TAG_VERSION }}
      credentials:
        username: kotori316
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set forge version
        run: echo "CI_FORGE=$(cat /forge.txt)" >> $GITHUB_ENV
      # FluidTank
      - name: Checkout FluidTank
        uses: actions/checkout@v3
        with:
          repository: 'Kotori316/FluidTank'
          ref: '${{ env.BRANCH }}'
          path: fluidtank
      - name: Permission of gradlew
        run: chmod +x ./gradlew
        working-directory: fluidtank
      - name: Test FluidTank
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: test copyGameTestTemplate runGameTestServer
          build-root-directory: fluidtank
      # QuarryPlus
      - name: Checkout QuarryPlus
        uses: actions/checkout@v3
        with:
          repository: 'Kotori316/QuarryPlus'
          ref: '${{ env.BRANCH }}'
          path: quarryplus
      - name: Permission of gradlew
        run: chmod +x ./gradlew
        working-directory: quarryplus
      - name: Test QuarryPlus
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: test copyGameTestTemplate runGameTestServer
          build-root-directory: quarryplus
