name: Build
on:
  push:
    paths:
      - "app/**"
      - "v-get/**"
      - ".github/workflows/build.yml"
      - "Dockerfile"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Check Java Toolchain and Dependencies
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: |
            javaToolchains 
            --warning-mode all 
            dependencies 
            :app:dependencies
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: test
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: build/reports/tests/*

  build:
    runs-on: ubuntu-latest
    env:
      MC_VERSION: 1.19
      JAVA_VERSION: 17
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image name
        run: |
          i=ghcr.io/${{ github.repository }}/fictional-meme
          echo "IMAGE_NAME=${i,,}" >> $GITHUB_ENV
          t=${{ env.MC_VERSION }}
          echo "TAG=${t,,}" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:latest
          load: true
          build-args: |
            MINECRAFT_VERSION=${{ env.MC_VERSION }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            PARCHMENT_MINECRAFT_VERSION=1.19.2
      - name: Check java version
        run: |
          docker images
          docker run --rm ${IMAGE_NAME}:${TAG} java --version
          echo "::group::Module List"
          docker run --rm ${IMAGE_NAME}:${TAG} java --list-modules
          echo "::endgroup::"
      - name: Check forge version
        run: |
          jar_path=$(docker run --rm ${IMAGE_NAME}:${TAG} find / -maxdepth 1 -name fictional-meme*.jar)
          echo "Found jar file at $jar_path"
          echo "Latest version of forge"
          docker run --rm ${IMAGE_NAME}:${TAG} java -jar $jar_path
          echo "Latest version of Minecraft ${{ env.MC_VERSION }}"
          docker run --rm ${IMAGE_NAME}:${TAG} java -jar $jar_path ${{ env.MC_VERSION }}
      - name: Check version list script
        run: | 
          set -eu
          a=$(docker run --rm ${IMAGE_NAME}:${TAG} /list_version.sh "${URL}")
          echo "$a" | grep 19
        env:
          URL: https://pkgs.dev.azure.com/Kotori316/minecraft/_packaging/mods/maven/v1/com/kotori316/additionalenchantedminer/maven-metadata.xml
      - name: Check cache version
        run: |
          docker run --rm ${IMAGE_NAME}:${TAG} cat /forge.txt
          docker run --rm ${IMAGE_NAME}:${TAG} cat /parchment_version.txt
      - name: Push1
        run: docker push ${IMAGE_NAME}:${TAG}
      - name: Push2
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push ${IMAGE_NAME}:latest
