name: Build
on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image name
        run: |
          i=docker.pkg.github.com/${{ github.repository }}/fictional-meme
          echo "IMAGE_NAME=${i,,}" >> $GITHUB_ENV
          t=${{ env.MC_VERSION }}
          echo "TAG=${t,,}" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          load: true
          build-args: |
            MINECRAFT_VERSION:${{ env.MC_VERSION }}
      - name: Check java version
        run: |
          docker images
          docker run --rm ${IMAGE_NAME}:${TAG} java --version
          echo "::group::Module List"
          docker run --rm ${IMAGE_NAME}:${TAG} java --list-modules
          echo "::endgroup::"
          jar_path=$(docker run --rm ${IMAGE_NAME}:${TAG} find / -maxdepth 1 -name *.jar)
          echo "Found jar file at $jar_path"
          echo "Latest version of forge"
          docker run --rm ${IMAGE_NAME}:${TAG} java -jar $jar_path
          docker tag ${IMAGE_NAME}:${TAG} ${IMAGE_NAME}:latest
      - name: Push
        run: docker push ${IMAGE_NAME}:${TAG} && docker push ${IMAGE_NAME}:latest
