name: Weekly Cleaner

on:
  schedule:
    - cron: "0 6 * * TUE"
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Get script
        run: curl -LO https://raw.githubusercontent.com/Kotori316/fictional-meme/master/clean_container.py
      - name: Install Python dependencies
        run: python3 -m pip install requests
      - name: Clean fictional-meme
        run: python3 ./clean_container.py
        env:
          USER_NAME: Kotori316
          PACKAGE_NAME: fictional-meme%2Ffictional-meme
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean dlcount
        run: python3 ./clean_container.py
        env:
          USER_NAME: Kotori316
          PACKAGE_NAME: DownloadCounts%2Fdlcount
          TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
      - name: Clean dlcount-daily
        run: python3 ./clean_container.py
        env:
          USER_NAME: Kotori316
          PACKAGE_NAME: dlcount-daily
          TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
