name: Weekly Build for 1.17.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MC_VERSION: 1.17.1
      JAVA_VERSION: 16
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image name
        run: |
          i=ghcr.io/${{ github.repository }}/fictional-meme
          echo "IMAGE_NAME=${i,,}" >> $GITHUB_ENV
          t=${{ env.MC_VERSION }}
          echo "TAG=${t,,}" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          push: true
          build-args: |
            MINECRAFT_VERSION=${{ env.MC_VERSION }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
